config/routes.rb
Rails.application.routes.draw do

	devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

	scope '(:locale)', constraints: { locale: /\w{2}/ } do

		devise_for :users, skip: :omniauth_callbacks, :controllers => {
			registrations: "users/registrations",
			sessions: "users/sessions",
			passwords: "users/passwords",
			confirmations: "users/confirmations",
			unlocks: "users/unlocks",
			mailer: "users/mailer"
		}

		root to: "homes#show"

		resource :home, only: [:show]

		resources :users, only: [:show] do
			collection do
				get 'profile'
				put 'edit_profile'
				get 'account_setting'
				put 'inactive_account'
			end
			resources :messages, only: [:index, :new, :create, :show] do
				collection do
					post 'first_create'
				end
			end
			resources :clients, only: [:edit, :update] do
				resources :client_contacts, only: [:new, :create] do
					collection do
						get 'first_new'
						post 'first_create'
					end
				end
				resources :client_schedules, only: [:index, :create] do
					collection do
						delete 'r_destroy'
					end
				end
			end
		end

		resources :clients, only: [:index, :show] do
			collection do
				get 'pre_month'
				get 'next_month'
			end
			resources :client_portfolios, only: [:new, :create] do
				collection do
					delete 'r_destroy'
				end
			end
		end

		resources :customers, only: [:show]

		resources :events, only: [:new, :create, :show, :edit, :update] do
			collection do
				get 'cs_past'
				get 'cs_future'
				get 'cl_past'
				get 'cl_future'
			end
			resources :event_states, only: []  do
				collection do
					post 'cl_accept'
					post 'cl_deliver'
					post 'cs_recieve'
					post 'cl_edit'
					post 'cs_accept'
					post 'cl_dismiss'
					post 'cs_dismiss'
					post 'cs_cancele'
					post 'cs_request_cancele'
					post 'cl_cancele'
				end
			end
			resources :event_photos, only: [:create] do
				collection do
					delete 'r_destroy'
					get 'zip_dl'
				end
			end
			resources :event_reviews, only: [:create, :update]
		end

		resource :about, only: [:show] do
			collection do
				get 'terms_of_service_cl'
				get 'terms_of_service_cs'
				get 'to_be_a_cameraman'
				get 'how_to_use'
				get 'use_with_phone'
				get 'contact_us'
			end
		end

		resource :helps, only: [:index] do
			collection do
				get 'to_receive_email'
			end
		end

		resources :categories, only: [] do
			collection do
				get 'profile'
				get 'id_photo'
				get 'wedding'
				get 'traveling'
				get 'daily_life'
				get 'seven_five_three'
				get 'coming_of_age'
				get 'maternity'
				get 'new_born'
				get 'commodities'
				get 'event'
				get 'pet'
			end
		end
	end
end

app/models/message.rb
class Message < ApplicationRecord

	scope :user_sends, -> id { where(sender_id: id)}
	scope :user_recirves, -> id { where(reciever_id: id) }
	scope :order_new, -> { order("created_at DESC") }
	scope :order_old, -> { order("created_at ASC") }

	# scope :user_sends, -> id { where(sender_id: id).group(:sender_id)}
	# scope :user_recirves, -> id { where(reciever_id: id).group(:reciever_id) }

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :user_check, only: [:index, :show]
	before_action :login_check, only: [:new]

	def new
		import_current_user

		@msg = Message.new
		@reciever = User.find(user_params)
	end

	def first_create
		Message.create(first_create_params)
		redirect_to user_message_path(current_user.id, user_params)

		# 通知メール
		reciever = User.find(first_create_params[:reciever_id])
		if reciever.mail_refused == false
			message = first_create_params[:message]
			mail = reciever.email
			name = User.find(first_create_params[:sender_id]).name
			MessageMailer.recieved(message, mail, name).deliver_now
		end
	end

	def index
		import_current_user

		#-------- left-menu --------#
		@msges = Message.user_sends(current_user.id).or(Message.user_recirves(current_user.id)).order_new

		ids = []
		for ms in @msges
			ids << ms.sender_id
			ids << ms.reciever_id
		end
		user_ids = ids.uniq
		user_ids.delete(current_user.id)
		@users = User.where(id: user_ids).order(['field(id, ?)', user_ids])
	end

	def show
		import_current_user

		#-------- left-menu --------#
		@msges = Message.user_sends(current_user.id).or(Message.user_recirves(current_user.id)).order_new

		ids = []
		for ms in @msges
			ids << ms.sender_id
			ids << ms.reciever_id
		end
		user_ids = ids.uniq
		user_ids.delete(current_user.id)
		@users = User.where(id: user_ids).order(['field(id, ?)', user_ids])


		#-------- right-content --------#
		# user
		@comunitating_user = User.find(id_params)
		@cs_here = @comunitating_user.customer
		@cl_here = @comunitating_user.client
		@categories = @cl_here.client_categories.includes(:category)
		@locations = @cl_here.client_locations.includes(:prefecture)
		@prim_price = @cl_here.client_primary_prices.active.first
		@options = @cl_here.client_option_prices.active

		#messages
		@selected_msges = Message.user_sends(current_user.id).user_recirves(id_params).or(Message.user_recirves(current_user.id).user_sends(id_params)).order_new

		# form用
		@msg = Message.new

		@locale = params[:locale]
	end

	def create
		Message.create(create_params)

		redirect_to user_message_path(current_user.id, reciever_params)

		# 通知メール
		reciever = User.find(create_params[:reciever_id])
		if reciever.mail_refused == false
			message = create_params[:message]
			mail = reciever.email
			name = User.find(create_params[:sender_id]).name
			MessageMailer.recieved(message, mail, name).deliver_now
		end
	end


private
	def user_params
		params[:user_id]
	end

	def id_params
		params[:id]
	end

	def reciever_params
		params[:message][:reciever_id]
	end

	def first_create_params
		params.require(:message).permit(:message).merge(sender_id: current_user.id, reciever_id: params[:user_id])
	end

	def create_params
		params.require(:message).permit(:message, :reciever_id).merge(sender_id: current_user.id)
	end


	def user_check
		unless user_signed_in? && params[:user_id].to_i == current_user.id
			flash[:alert] = t(".Please_login")
			redirect_to root_path
		end
	end

	def login_check
		unless user_signed_in?
			flash[:alert] = t(".Please_login")
			redirect_to root_path
		end
	end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_message_menu.html.erb
<div class="ms-menu col-12 col-md-4 col-lg-3">
	<hr>
	<% users.each do |user| %>
		<div class="container-fluid">
			<%= link_to user_message_path(current_user.id, user.id), class: "" do %>
				<div class="row">
					<div class="col-3">
						<%= image_tag user.image.url(:thumb), :alt => "icon", :class => "ms-menu-icon" if user.image? %>
					</div>
					<div class="col-9">
						<%= user.name %>
					</div>
				</div>
			<% end %>
		</div>
		<hr>
	<% end %>
</div>

app/views/messages/_message_menu_sm.html.erb
<div class="ms-menu col-12 col-md-4 col-lg-3 d-none d-md-block">
	<hr>
	<% users.each do |user| %>
		<div class="container-fluid">
			<%= link_to user_message_path(current_user.id, user.id), class: "" do %>
				<div class="row">
					<div class="col-3">
						<%= image_tag user.image.url(:thumb), :alt => "icon", :class => "ms-menu-icon" if user.image? %>
					</div>
					<div class="col-9">
						<%= user.name %>
					</div>
				</div>
			<% end %>
		</div>
		<hr>
	<% end %>
</div>

app/views/messages/index.html.erb
<div class="row">
	<!-- left memu -->
	<%= render :partial => 'messages/message_menu', :locals=>{users: @users} %>
	<!-- 真ん中 -->
	<div class="ms-content col-12 col-md-8 col-lg-9  d-none d-md-block message-wrapper">
	</div>
</div>

<% assign_meta_tags title: t(".meta_title"),
                    description: t(".meta_description"),
                    keywords: t(".meta_keywords") %>
<% set_meta_tags noindex: true %>

app/views/messages/new.html.erb
<div class="container">
	<div class="ms-new clearfix">
		<%= form_for @msg,:url => {:action => :first_create} do |f| %>
			<%= image_tag @reciever.image.thumb.url, alt: "icon", class: "image" if @reciever.image? %><br>
			<h1><%=t(".message", name: @reciever.name) %></h1>
			<%= f.text_area :message %>
			<div class="send-btn">
				<%= f.submit t(".send_btn"), class: "prim-btn" %>
			</div>
		<% end %>
	</div>
</div>

<% assign_meta_tags title: t(".meta_title", name: @reciever.name),
                    description: t(".meta_description"),
                    keywords: t(".meta_keywords") %>
<% set_meta_tags noindex: true %>

app/views/messages/show.html.erb
<div class="row">
	<!-- left memu -->
	<%= render :partial => 'messages/message_menu_sm', :locals=>{users: @users} %>
	<!-- 真ん中 -->
	<div class="ms-user col-lg-3 d-none d-lg-block">
		<div class="ms-user-upper">
			<h2><%= @comunitating_user.name %></h2>
			<% if @cl_here.user.image? %>
				<%= image_tag @cl_here.user.image.url(:thumb), alt: "icon", class: "ms-user-icon" %>
			<% else %>
				<%= render :partial => 'svgs/baby_80' %>
			<% end %>
		</div>
		<div class="ms-user-lower">
			<div class="line-break"><%= render :partial => 'clients/introduction', :locals=>{cl: @cl_here, locale: @locale} %></div>
			<br>

			<!-- カテゴリー -->
			<% if @categories.present? %>
				<h2><%= render :partial => 'svgs/category' %>&nbsp;<%= t(".Photographing_Categories") %></h2>
				<div class="badges">
					<% @categories.each do |cate| %>
						<span class="badge badge-pill subprime-badge"><%= cate.category.ja %></span>
					<% end %>
				</div>
			<% end %>
			<br>

			<!-- 撮影エリア -->
			<% if @locations.present? %>
				<h2><%= render :partial => 'svgs/location' %>&nbsp;<%= t(".Photographing_Area") %></h2>
				<div class="badges">
					<% @locations.each do |location| %>
						<span class="badge badge-pill black-badge"><%= location.prefecture.ja %></span>
					<% end %>
				</div>
			<% end %>
			<br>

			<% if @prim_price.present? %>
				<% if @prim_price.price_per_hour.present? %>
					<h2><%= render :partial => 'svgs/fee' %>&nbsp;<%= t(".Price") %></h2>
					<p><%= @prim_price.price_per_hour %>円/時間&nbsp;（<%= @prim_price.minimum_hours %>時間から受け付けます）</p>
				<% end %>
			<% end %>
			<br>

			<% if @options.present? %>
				<h2><%= render :partial => 'svgs/cart' %>&nbsp;<%= t(".Option_memu") %></h2>
				<% @options.each do |option| %>
					<p>
						<%= option.name %>
						<% if option.along_with_time == "1" %>
							<%= t(".price_per_hour") %>
						<% end %>
						<%= option.price %>
					</p>
				<% end %>
			<% end %>
			<br>

			<% if @cl_here.camera.present? %>
				<h2><%= render :partial => 'svgs/camera' %>&nbsp;<%= t(".Camera") %></h2>
				<pre class="indent"><%= @cl_here.camera %></pre>
			<% end %>

			<!-- 納品写真 -->
			<% if @cl_here.deliverables.present? %>
				<h2><%= render :partial => 'svgs/deliverables' %>&nbsp;<%= t(".deliverables") %></h2>
				<pre class="indent"><%= @cl_here.deliverables %></pre>
			<% end %>

			<% if @cl_here.message? %>
				<h2><%= render :partial => 'svgs/message' %>&nbsp;<%= t(".Message") %></h2>
				<pre class="indent"><%= @cl_here.message %></pre>
			<% end %>
		</div>
	</div>
	<div class="ms-content col-12 col-md-8 col-lg-6">
		<div class="container-fluid">
			<div class="ms-content-upper d-lg-none">
				<%= link_to "＜", user_messages_path(current_user), class: "return-btn" %>
				<%= link_to client_path(@cl_here) do%>
					<%= image_tag @comunitating_user.image.url(:thumb), :alt => "icon", :class => "ms-content-icon" if @comunitating_user.image? %>
				<% end %>
			</div>
			<hr>
			<div class="ms-content-middle">
				<div class="ms-content-new">
					<%= form_for @msg,:url => {:action => :create} do |f| %>
						<%= f.hidden_field :reciever_id, :value => @comunitating_user.id %>
						<%= f.text_area :message, placeholder: t(".write_here") %>
						<div class="send-btn clearfix">
							<%= f.submit t(".send_btn"), class: "prim-btn" %>
						</div>
						<hr>
					<% end %>
				</div>
			</div>
			<div class="ms-content-lower">
				<div class="ms-content-lower-time">
					<%= t(".last_message") %> : <%= @selected_msges.first.created_at %>
				</div>
				<% @selected_msges.each do |msg| %>
					<% if msg.sender_id == current_user.id %>
						<p class="right_balloon"><%= msg.message %></p>
					<% else %>
						<p class="left_balloon"><%= msg.message %></p>
					<% end %>
				<% end %>
				<br class="clear_balloon"/>
			</div>
		</div>
	</div>
</div>

<% assign_meta_tags title: t(".meta_title", name: @comunitating_user.name),
                    description: t(".meta_description"),
                    keywords: t(".meta_keywords", name: @comunitating_user.name) %>
<% set_meta_tags noindex: true %>