config/routes.rb
Rails.application.routes.draw do

	devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

	scope '(:locale)', constraints: { locale: /\w{2}/ } do

		devise_for :users, skip: :omniauth_callbacks, :controllers => {
			registrations: "users/registrations",
			sessions: "users/sessions",
			passwords: "users/passwords",
			confirmations: "users/confirmations",
			unlocks: "users/unlocks",
			mailer: "users/mailer"
		}

		root to: "homes#show"

		resource :home, only: [:show]

		resources :users, only: [:show] do
			collection do
				get 'profile'
				put 'edit_profile'
				get 'account_setting'
				put 'inactive_account'
			end
			resources :messages, only: [:index, :new, :create, :show] do
				collection do
					post 'first_create'
				end
			end
			resources :clients, only: [:edit, :update] do
				resources :client_contacts, only: [:new, :create] do
					collection do
						get 'first_new'
						post 'first_create'
					end
				end
				resources :client_schedules, only: [:index, :create] do
					collection do
						delete 'r_destroy'
					end
				end
			end
		end

		resources :clients, only: [:index, :show] do
			collection do
				get 'pre_month'
				get 'next_month'
			end
			resources :client_portfolios, only: [:new, :create] do
				collection do
					delete 'r_destroy'
				end
			end
		end

		resources :customers, only: [:show]

		resources :events, only: [:new, :create, :show, :edit, :update] do
			collection do
				get 'cs_past'
				get 'cs_future'
				get 'cl_past'
				get 'cl_future'
			end
			resources :event_states, only: []  do
				collection do
					post 'cl_accept'
					post 'cl_deliver'
					post 'cs_recieve'
					post 'cl_edit'
					post 'cs_accept'
					post 'cl_dismiss'
					post 'cs_dismiss'
					post 'cs_cancele'
					post 'cs_request_cancele'
					post 'cl_cancele'
				end
			end
			resources :event_photos, only: [:create] do
				collection do
					delete 'r_destroy'
					get 'zip_dl'
				end
			end
			resources :event_reviews, only: [:create, :update]
		end

		resource :about, only: [:show] do
			collection do
				get 'terms_of_service_cl'
				get 'terms_of_service_cs'
				get 'to_be_a_cameraman'
				get 'how_to_use'
				get 'use_with_phone'
				get 'contact_us'
			end
		end

		resource :helps, only: [:index] do
			collection do
				get 'to_receive_email'
			end
		end

		resources :categories, only: [] do
			collection do
				get 'profile'
				get 'id_photo'
				get 'wedding'
				get 'traveling'
				get 'daily_life'
				get 'seven_five_three'
				get 'coming_of_age'
				get 'maternity'
				get 'new_born'
				get 'commodities'
				get 'event'
				get 'pet'
			end
		end
	end
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :timeoutable, :omniauthable

  #メール認証外す
  # devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable

	has_one :customer
	has_one :client
	has_many :user_languages
	accepts_nested_attributes_for :user_languages

  scope :intro_present, -> { where.not(introduction_ja: nil).or(where.not(introduction_en: nil).or(where.not(introduction_zh: nil).or(where.not(introduction_tw: nil))))}


	# ファイルアップロード処理
	mount_uploader :image, ImageUploader


  def soft_delete
    update(deleted_at: Time.now)
  end

  #論理消去されたユーザーをログイン不可に
  def active_for_authentication?
    super && !deleted_at && (!confirmation_required? || confirmed? || confirmation_period_valid?)
  end
  def inactive_message
    !deleted_at ? super : :deleted_account
  end

  # trueだと、ブラウザ閉じてもログイン保持できる
  def remember_me
    true
  end

	# userがいなければfacebookアカウントでuserを作成するメソッド
  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        # userモデルが持っているカラムをそれぞれ定義していく
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name
        user.remote_image_url = auth.info.image.gsub('http://','https://')
        user.uid = auth.uid
        user.provider = auth.provider

        # If you are using confirmable and the provider(s) you use validate emails,
        # uncomment the line below to skip the confirmation emails.
        user.skip_confirmation!
      end
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super do |resource|
      sign_in(resource)
    end
  end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/mailer.rb
class Users::Mailer < Devise::Mailer
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    #CL,CS発番
    unless @user.client.present?
      Client.create(user_id: @user.id)
    end
    unless @user.customer.present?
      Customer.create(user_id: @user.id)
    end

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end


  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    import_current_user

    # super
    my_build_resource({})
    self.resource.user_languages.build
    yield resource if block_given?
    respond_with resource
  end

  # POST /resource
  def create
    # super
    user = my_build_resource(sign_up_params)
    resource.save

    #User_languageの更新
    if resource.persisted? && user_language_params != nil
      # language_ids = user_language_params
      user_language_params.each do |id|
        UserLanguage.create(user_id: user.id, language_id: id.to_i)
      end
    end

    #CL,CS発番
    customer = Customer.create(user_id: user.id)
    client = Client.create(user_id: user.id)

    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)

        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end

  end

  # GET /resource/edit
  def edit
    # super

    # menu用
    import_current_user

    # content用
    user_languages = current_user.user_languages
    @lang_ids = []
    for user_language in user_languages
      @lang_ids << user_language.language_id
    end
  end

  # PUT /resource
  def update
    #super

    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)

    yield resource if block_given?
    if resource_updated
      if is_flashing_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
          :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      bypass_sign_in resource, scope: resource_name
      respond_with resource, location: edit_user_registration_path
      # respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
  def my_build_resource(hash=nil)
    self.resource = resource_class.new_with_session(hash || {}, session)
  end

  #user編集の際にパスワード入力をなくす
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def user_language_params
    params[:language_id]
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    # super

    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?

    if search_result_params[:redirect_client_id].present?
      redirect_to new_user_message_path(current_user.id, search_result_params[:redirect_client_id])
    elsif search_result_params[:rv_redirect_client_id].present?
      redirect_to new_event_path(id: search_result_params[:rv_redirect_client_id])
    else
      respond_with resource, location: after_sign_in_path_for(resource)
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def search_result_params
    params.require(:user).permit(:redirect_client_id, :rv_redirect_client_id)
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	# before_action :authenticate_user!, only: :show
	before_action :user_check, only: :show
	before_action :login_check, only: [:profile, :edit_profile, :account_setting]


	def show
		#user_info
		@user = current_user
		langs = @user.user_languages.includes(:language)
		@mylangs = []
		langs.each do |lang|
			@mylangs << lang.language
		end

		#client_info
		@cl = @user.client
		@cl_categories = @cl.client_categories.includes(:category)
		@cl_prim_price = @cl.client_primary_prices.active.first
		@cl_opt_prices = @cl.client_option_prices.active
		@cl_locations = @cl.client_locations.includes(:prefecture)
		@cl_prefectures = []
		for cl_locations in @cl_locations
			@cl_prefectures << cl_locations.prefecture
		end
		@portfolio_nums = @cl.client_portfolios.active.count

		#schedule.present?
		@cl_schedules = @cl.client_schedules.future.available

		#customer_info
		@cs = @user.customer

		#event
		cl_evs = @cl.events.includes(:event_review, customer: :user)
		cl_evs_future = cl_evs.future
		@cl_future = []
		for ev in cl_evs_future do
			if ev.event_states.last.state == "request"
				@cl_future << ev
			end
		end
		cl_evs_past = cl_evs.past
		@cl_past = []
		for ev in cl_evs_past do
			if ev.event_states.last.state.in?(['cl_accepted','cs_accepted'])
				@cl_past << ev
			end
		end
		@cl_reviews = []
		for ev in cl_evs_past do
			if ev.event_states.last.state.in?(['cl_delivered', 'cs_recieved']) && (ev.event_review == nil || ev.event_review.cl_review == nil)
				@cl_reviews << ev
			end
		end


		cs_evs = @cs.events.includes(:event_review, client: :user)
		cs_evs_future = cs_evs.future
		@cs_future = []
		for ev in cs_evs_future do
			if ev.event_states.last.state == "cl_edited"
				@cs_future << ev
			end
		end
		cs_evs_past = cs_evs.past
		@cs_past = []
		for ev in cs_evs_past do
			if ev.event_states.last.state == "cl_delivered"
				@cs_past << ev
			end
		end

		@cs_reviews = []
		for ev in cs_evs_past do
			if ev.event_states.last.state.in?(['cs_recieved']) && (ev.event_review == nil || ev.event_review.cs_review == nil)
				@cs_reviews << ev
			end
		end
	end

	def profile
		# menu用
		import_current_user

		# content用
		user_languages = current_user.user_languages
		@lang_ids = []
		for user_language in user_languages
			@lang_ids << user_language.language_id
		end
	end

	def edit_profile
		# imageの更新
		if edit_profile_params.present?
			current_user.update(edit_profile_params)
		end

		#User_languageの更新
		unless user_language_params == nil
			#元のlangを取得
			pre_user_languages = current_user.user_languages
			pre_lang_ids = []
			for user_language in pre_user_languages
				pre_lang_ids << user_language.language_id
			end

			#変更するlangと照らし合わせて更新
			language_ids = user_language_params
			language_ids.each do |id|
				unless pre_lang_ids.include?(id.to_i)
					UserLanguage.create(user_id: current_user.id, language_id: id.to_i)
				end
			end
			pre_lang_ids.each do |pre_id|
				unless language_ids.include?(pre_id.to_s)
					UserLanguage.where(user_id: current_user.id, language_id: pre_id.to_i).destroy_all
				end
			end
		end

		# 自己紹介の更新
		current_user.customer.update(introduction: cs_intro_params)

		flash[:alert] = t(".Setting_has_updated")
		redirect_to profile_users_path
	end


	def account_setting
		# menu用
		import_current_user
	end

	def inactive_account
		import_current_user

		@user.soft_delete
		@cl.soft_delete
		@cs.soft_delete
		sign_out(@user)
		redirect_to home_path
	end


private
	def user_language_params
		params[:language_id]
	end

	def edit_profile_params
		if params[:user].present?
			params.require(:user).permit(:image)
		end
	end

	def cs_intro_params
		params[:introduction]
	end


	def login_check
		unless user_signed_in?
			flash[:alert] = t(".Please_login")
			redirect_to root_path
		end
	end

	def user_check
		unless user_signed_in? && params[:id].to_i == current_user.id
			flash[:alert] = t(".Please_login")
			redirect_to root_path
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_mypage_menu_camera.html.erb
<div class="row">
  <div class="col-2 offset-2">
    <%= link_to user_client_client_schedules_path(user, cl, day: Date.today ) do %>
      <% if page == "cl-schedule" %>
        <p class="selected">&emsp;<%= t(".cl_schedule") %></p>
      <% else %>
        <p class="under-marker-grey">&emsp;<%= t(".cl_schedule") %></p>
      <% end %>
    <% end %>
  </div>
  <div class="col-2">
    <%= link_to edit_user_client_path(user, cl) do %>
      <% if page == "cl-edit" %>
        <p class="selected">&emsp;<%= t(".cl_settings") %></p>
      <% else %>
        <p class="under-marker-grey">&emsp;<%= t(".cl_settings") %></p>
      <% end %>
    <% end %>
  </div>
  <div class="col-2">
    <%= link_to new_client_client_portfolio_path(cl) do %>
      <% if page == "cl-portfolio" %>
        <p class="selected">&emsp;<%= t(".upload_cl_portpolios") %></p>
      <% else %>
        <p class="under-marker-grey">&emsp;<%= t(".upload_cl_portpolios") %></p>
      <% end %>
    <% end %>
  </div>
  <div class="col-2">
    <%= link_to new_user_client_client_contact_path(user, cl) do %>
      <% if page == "cl-contact" %>
        <p class="selected">&emsp;<%= t(".change_phone_number_adress") %></p>
      <% else %>
        <p class="under-marker-grey">&emsp;<%= t(".change_phone_number_adress") %></p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/_mypage_menu_camera_sm.html.erb
<%= link_to user_client_client_schedules_path(user, cl, day: Date.today ) do %>
  <% if page == "cl-schedule" %>
    <p class="selected">&emsp;<%= t(".cl_schedule") %></p>
  <% else %>
    <p class="under-marker-grey">&emsp;<%= t(".cl_schedule") %></p>
  <% end %>
<% end %>
<%= link_to edit_user_client_path(user, cl) do %>
  <% if page == "cl-edit" %>
    <p class="selected">&emsp;<%= t(".cl_settings") %></p>
  <% else %>
    <p class="under-marker-grey">&emsp;<%= t(".cl_settings") %></p>
  <% end %>
<% end %>
<%= link_to new_client_client_portfolio_path(cl) do %>
  <% if page == "cl-portfolio" %>
    <p class="selected">&emsp;<%= t(".upload_cl_portpolios") %></p>
  <% else %>
    <p class="under-marker-grey">&emsp;<%= t(".upload_cl_portpolios") %></p>
  <% end %>
<% end %>
<%= link_to new_user_client_client_contact_path(user, cl) do %>
  <% if page == "cl-contact" %>
    <p class="selected">&emsp;<%= t(".change_phone_number_adress") %></p>
  <% else %>
    <p class="under-marker-grey">&emsp;<%= t(".change_phone_number_adress") %></p>
  <% end %>
<% end %>

app/views/users/_mypage_menu_event.html.erb
<div class="row">
  <% if cl.consent == true %>
    <div class="col-4 offset-2">
      <p class="under-marker-grey"><%= t(".As_a_customer") %></p>
      <%= link_to cs_future_events_path do %>
        <% if page == "cs-future" %>
          <div class="selected mypage-subtitle-sub">
            &emsp;<%= t(".In_the_future") %>
          </div>
        <% else %>
          <div class="mypage-subtitle-sub">
            &emsp;<%= t(".In_the_future") %>
          </div>
        <% end %>
      <% end %>
      <%= link_to cs_past_events_path do %>
        <% if page == "cs-past" %>
          <div class="selected mypage-subtitle-sub">
            &emsp;<%= t(".In_the_past") %>
          </div>
        <% else %>
          <div class="mypage-subtitle-sub">
            &emsp;<%= t(".In_the_past") %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-4">
      <p class="under-marker-grey"><%= t(".As_a_cameraman") %></p>
      <%= link_to cl_future_events_path do %>
        <% if page == "cl-future" %>
          <div class="selected mypage-subtitle-sub">&emsp;<%= t(".As_a_cameraman_future") %></div>
        <% else %>
          <div class="mypage-subtitle-sub">&emsp;<%= t(".As_a_cameraman_future") %></div>
        <% end %>
      <% end %>
      <%= link_to cl_past_events_path do %>
        <% if page == "cl-past" %>
          <div class="selected mypage-subtitle-sub">&emsp;<%= t(".As_a_cameraman_past") %></div>
        <% else %>
          <div class="mypage-subtitle-sub">&emsp;<%= t(".As_a_cameraman_past") %></div>
      　<% end %>
      <% end %>
    </div>
  <% else %>
    <div class="col-2 offset-2">
      <%= link_to cs_future_events_path do %>
        <% if page == "cs-future" %>
          <div class="selected mypage-subtitle-sub">
            &emsp;<%= t(".In_the_future") %>
          </div>
        <% else %>
          <div class="under-marker-grey mypage-subtitle-sub">
            &emsp;<%= t(".In_the_future") %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-2">
      <%= link_to cs_past_events_path do %>
        <% if page == "cs-past" %>
          <div class="selected mypage-subtitle-sub">
            &emsp;<%= t(".In_the_past") %>
          </div>
        <% else %>
          <div class="under-marker-grey mypage-subtitle-sub">
            &emsp;<%= t(".In_the_past") %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/_mypage_menu_event_sm.html.erb
<% if cl.consent == true %>
  <p class="under-marker-grey"><%= t(".As_a_customer") %></p>
  <%= link_to cs_future_events_path do %>
    <% if page == "cs-future" %>
      <div class="selected mypage-subtitle-sub">
        &emsp;<%= t(".In_the_future") %>
      </div>
    <% else %>
      <div class="mypage-subtitle-sub">
        &emsp;<%= t(".In_the_future") %>
      </div>
    <% end %>
  <% end %>
  <%= link_to cs_past_events_path do %>
    <% if page == "cs-past" %>
      <div class="selected mypage-subtitle-sub">
        &emsp;<%= t(".In_the_past") %>
      </div>
    <% else %>
      <div class="mypage-subtitle-sub">
        &emsp;<%= t(".In_the_past") %>
      </div>
    <% end %>
  <% end %>
  <p class="under-marker-grey"><%= t(".As_a_cameraman") %></p>
  <%= link_to cl_future_events_path do %>
    <% if page == "cl-future" %>
      <div class="selected mypage-subtitle-sub">&emsp;<%= t(".As_a_cameraman_future") %></div>
    <% else %>
      <div class="mypage-subtitle-sub">&emsp;<%= t(".As_a_cameraman_future") %></div>
    <% end %>
  <% end %>
  <%= link_to cl_past_events_path do %>
    <% if page == "cl-past" %>
      <div class="selected mypage-subtitle-sub">&emsp;<%= t(".As_a_cameraman_past") %></div>
    <% else %>
      <div class="mypage-subtitle-sub">&emsp;<%= t(".As_a_cameraman_past") %></div>
  　<% end %>
  <% end %>
<% else %>
  <%= link_to cs_future_events_path do %>
    <% if page == "cs-future" %>
      <div class="selected mypage-subtitle-sub">
        &emsp;<%= t(".In_the_future") %>
      </div>
    <% else %>
      <div class="under-marker-grey mypage-subtitle-sub">
        &emsp;<%= t(".In_the_future") %>
      </div>
    <% end %>
  <% end %>
  <%= link_to cs_past_events_path do %>
    <% if page == "cs-past" %>
      <div class="selected mypage-subtitle-sub">
        &emsp;<%= t(".In_the_past") %>
      </div>
    <% else %>
      <div class="under-marker-grey mypage-subtitle-sub">
        &emsp;<%= t(".In_the_past") %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/users/_mypage_menu_user.html.erb
<div class="row">
  <div class="col-2 offset-2">
    <%= link_to profile_users_path do %>
      <% if page == "user-profile" %>
        <p class="selected">&emsp;<%= t(".edit_profile") %></p>
      <% else %>
        <p class="under-marker-grey">&emsp;<%= t(".edit_profile") %></p>
      <% end %>
    <% end %>
  </div>
  <div class="col-2">
    <%= link_to edit_user_registration_path do %>
      <% if page == "user-edit" %>
        <p class="selected">&emsp;<%= t(".settings") %></p>
      <% else %>
        <p class="under-marker-grey">&emsp;<%= t(".settings") %></p>
      <% end %>
    <% end %>
  </div>
  <div class="col-2">
    <%= link_to account_setting_users_path do %>
      <% if page == "user-account" %>
        <p class="selected">&emsp;<%= t(".account_settings") %></p>
      <% else %>
        <p class="under-marker-grey">&emsp;<%= t(".account_settings") %></p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/_mypage_menu_user_sm.html.erb
<%= link_to profile_users_path do %>
  <% if page == "user-profile" %>
    <p class="selected">&emsp;<%= t(".edit_profile") %></p>
  <% else %>
    <p class="under-marker-grey">&emsp;<%= t(".edit_profile") %></p>
  <% end %>
<% end %>
<%= link_to edit_user_registration_path do %>
  <% if page == "user-edit" %>
    <p class="selected">&emsp;<%= t(".settings") %></p>
  <% else %>
    <p class="under-marker-grey">&emsp;<%= t(".settings") %></p>
  <% end %>
<% end %>
<%= link_to account_setting_users_path do %>
  <% if page == "user-account" %>
    <p class="selected">&emsp;<%= t(".account_settings") %></p>
  <% else %>
    <p class="under-marker-grey">&emsp;<%= t(".account_settings") %></p>
  <% end %>
<% end %>