config/routes.rb
Rails.application.routes.draw do

	devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

	scope '(:locale)', constraints: { locale: /\w{2}/ } do

		devise_for :users, skip: :omniauth_callbacks, :controllers => {
			registrations: "users/registrations",
			sessions: "users/sessions",
			passwords: "users/passwords",
			confirmations: "users/confirmations",
			unlocks: "users/unlocks",
			mailer: "users/mailer"
		}

		root to: "homes#show"

		resource :home, only: [:show]

		resources :users, only: [:show] do
			collection do
				get 'profile'
				put 'edit_profile'
				get 'account_setting'
				put 'inactive_account'
			end
			resources :messages, only: [:index, :new, :create, :show] do
				collection do
					post 'first_create'
				end
			end
			resources :clients, only: [:edit, :update] do
				resources :client_contacts, only: [:new, :create] do
					collection do
						get 'first_new'
						post 'first_create'
					end
				end
				resources :client_schedules, only: [:index, :create] do
					collection do
						delete 'r_destroy'
					end
				end
			end
		end

		resources :clients, only: [:index, :show] do
			collection do
				get 'pre_month'
				get 'next_month'
			end
			resources :client_portfolios, only: [:new, :create] do
				collection do
					delete 'r_destroy'
				end
			end
		end

		resources :customers, only: [:show]

		resources :events, only: [:new, :create, :show, :edit, :update] do
			collection do
				get 'cs_past'
				get 'cs_future'
				get 'cl_past'
				get 'cl_future'
			end
			resources :event_states, only: []  do
				collection do
					post 'cl_accept'
					post 'cl_deliver'
					post 'cs_recieve'
					post 'cl_edit'
					post 'cs_accept'
					post 'cl_dismiss'
					post 'cs_dismiss'
					post 'cs_cancele'
					post 'cs_request_cancele'
					post 'cl_cancele'
				end
			end
			resources :event_photos, only: [:create] do
				collection do
					delete 'r_destroy'
					get 'zip_dl'
				end
			end
			resources :event_reviews, only: [:create, :update]
		end

		resource :about, only: [:show] do
			collection do
				get 'terms_of_service_cl'
				get 'terms_of_service_cs'
				get 'to_be_a_cameraman'
				get 'how_to_use'
				get 'use_with_phone'
				get 'contact_us'
			end
		end

		resource :helps, only: [:index] do
			collection do
				get 'to_receive_email'
			end
		end

		resources :categories, only: [] do
			collection do
				get 'profile'
				get 'id_photo'
				get 'wedding'
				get 'traveling'
				get 'daily_life'
				get 'seven_five_three'
				get 'coming_of_age'
				get 'maternity'
				get 'new_born'
				get 'commodities'
				get 'event'
				get 'pet'
			end
		end
	end
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :customer
	belongs_to :client
	belongs_to :prefecture

	has_one :event_review

	has_many :event_categories
	has_many :event_primary_prices
	has_many :event_option_prices
	accepts_nested_attributes_for :event_option_prices
	has_many :event_photos
	has_many :event_states
	has_many :client_reviews
	has_many :customer_reviews

  # def self.as_cl(client_id)
  #   where(client_id: client_id)
  # end
	scope :as_cl, -> client_id{ where(client_id: client_id) }
	scope :as_cs, -> customer_id{ where(customer_id: customer_id) }
	scope :request, ->  {
		joins(:event_states).merge(EventState.request)
	}
	scope :cl_edited, ->  {
		joins(:event_states).merge(EventState.cl_edited)
	}
	scope :accepted, ->  {
		joins(:event_states).merge(EventState.accepted)
	}
	scope :cl_edited, ->  {
		joins(:event_states).merge(EventState.cl_edited)
	}
	scope :cl_delivered, ->  {
		joins(:event_states).merge(EventState.cl_delivered)
	}
	scope :future, ->  { where("start_time > ?", Time.now())}
	scope :past, ->  { where("start_time <= ?", Time.now())}
	scope :cs_reviewed, ->  {
		joins(:event_review).merge(EventReview.cs_reviewed)
	}
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :login_check, only: [:new, :create, :cs_future, :cs_past, :cl_future, :cl_past]
	before_action :event_show_user_check, only: [:show]
	before_action :event_edit_user_check, only: [:edit]
	before_action :update_user_check, only: [:update]


	def cs_future
		import_current_user
		@events = Event.as_cs(@cs.id).future.request.includes(:prefecture, client: :user).order(start_time: :DESC)
	end

	def cs_past
		import_current_user
		@events = Event.as_cs(@cs.id).past.request.includes(:prefecture, :event_review, client: :user).order(start_time: :DESC)
	end

	def cl_future
		import_current_user
		@events = Event.as_cl(@cl.id).future.request.includes(:prefecture, customer: :user).order(start_time: :DESC)
	end

	def cl_past
		import_current_user
		@events = Event.as_cl(@cl.id).past.request.includes(:prefecture, :event_review, customer: :user).order(start_time: :DESC)
	end


	def new
		import_current_user

		@cl_here = Client.find(id_params)
		@categories = @cl_here.client_categories.includes(:category)
		@langs = @cl_here.user.user_languages.includes(:language)
		@locations = @cl_here.client_locations.includes(:prefecture)
		@prim_price = @cl_here.client_primary_prices.active.first
		@options = @cl_here.client_option_prices.active
		@portfolios = @cl_here.client_portfolios

		######### カレンダー ###########
		@day = Date.today

		from_date = Date.new(@day.year, @day.month, @day.beginning_of_month.day).beginning_of_week(:sunday)
		to_date = Date.new(@day.year, @day.month, @day.end_of_month.day).end_of_week(:sunday)

		# カレンダーを書く用
		@c_dates = []
		(from_date..to_date).each do |d|
			sch = ClientSchedule.find_by(client_id: @cl_here.id, date: d)

			date = {}
			date["date"] = d
			if sch.present?
				date["schedule"] = sch.schedule
			end
			@c_dates << date
		end


		######### インスタンス渡す ########
		@event = Event.new
		@event.event_option_prices.build
	end

	def edit
		import_current_user

		@event = Event.find(id_params)
		@ev_date = @event.start_time.to_date
		@ev_prim_price = @event.event_primary_prices.last
		@prim_price = @event.event_primary_prices.last.client_primary_price
		@ev_options = @event.event_option_prices.includes(:client_option_price)
		@ev_opt_ids = []
		for opt in @ev_options do
			@ev_opt_ids << opt.client_option_price_id
		end

		@cl_here = Client.find(client_id_params)
		@options = @cl_here.client_option_prices.active
		opt_ids = []
		for opt in @options do
			opt_ids << opt.id
		end
		@opt_diff = opt_ids - @ev_opt_ids

		######### カレンダー ###########
		@day = Date.today

		from_date = Date.new(@day.year, @day.month, @day.beginning_of_month.day).beginning_of_week(:sunday)
		to_date = Date.new(@day.year, @day.month, @day.end_of_month.day).end_of_week(:sunday)

		# カレンダーを書く用
		@c_dates = []
		(from_date..to_date).each do |d|
			sch = ClientSchedule.find_by(client_id: @cl_here.id, date: d)

			date = {}
			date["date"] = d
			if sch.present?
				date["schedule"] = sch.schedule
			end
			@c_dates << date
		end

		@i = 0
		@x = 1000
		@y = 1000
	end

	def create
		# イベント作成
		if ev_create_params.kind_of?(String) then
			if ev_create_params == "time-error" then
				flash[:alert] = t(".Requested_time_is_invalid")
				redirect_to new_event_path(id: event_client_id_params)
			elsif ev_create_params == "total-fee-error" then
				flash[:alert] = t(".Requested_price_is_invalid")
				redirect_to new_event_path(id: event_client_id_params)
			else
				flash[:alert] = t(".Requested_option_menu_is_invalid")
				redirect_to new_event_path(id: event_client_id_params)
			end
		else
			event = Event.create(ev_create_params)

			# ev_prim_price_table
			prim_price = ev_prim_price_params.merge(event_id: event.id)
			EventPrimaryPrice.create(prim_price)

			# ev_opt_price_table
			if ev_opt_price_params != 0
				for opt in ev_opt_price_params do
					opt_price = opt.merge(event_id: event.id)
					EventOptionPrice.create(opt_price)
				end
			end

			# ev_states_table
			EventState.create(event_id: event.id, state: "request")

			# 通知メール
			reciever = Client.find(event_client_id_params).user
			sender = current_user
			if reciever.mail_refused == false
				message = ev_create_params[:message]
				day = ev_hours_params["start_time"].strftime('%Y/%m/%d')
				wday = l(day.to_date, format: :wday)
				start_time = ev_hours_params["start_time"].strftime('%H:%M')
				end_time  = ev_hours_params["end_time"].strftime('%H:%M')
				prefecture = Prefecture.find(ev_create_params[:prefecture_id]).ja
				location_detail = ev_create_params[:location_detail]
				num_people = ev_create_params[:num_people]
				total_price = ev_create_params[:total_price]
				primary_price_sum = ev_create_params[:primary_price_sum]
				options = event.event_option_prices
				reciever_mail = reciever.email
				sender_name = sender.name
				link = 'https://www.camera-to-culture.com/' + event.id.to_s
				ReserveMailer.cs_requested(message, day, wday, start_time, end_time, prefecture, location_detail, num_people, total_price, primary_price_sum, options, reciever_mail, sender_name, link).deliver_now
			end

			redirect_to event_path(event)
		end
	end

	def update
		# イベント作成
		if ev_edit_params.kind_of?(String) then
			if ev_edit_params == "time-error" then
				flash[:alert] = t(".Requested_time_is_invalid")
				redirect_to new_event_path(id: event_client_id_params)
			elsif ev_edit_params == "total-fee-error" then
				flash[:alert] = t(".Requested_price_is_invalid")
				redirect_to new_event_path(id: event_client_id_params)
			else
				flash[:alert] = t(".Requested_option_menu_is_invalid")
				redirect_to new_event_path(id: event_client_id_params)
			end
		else
			event = Event.find(id_params)
			event.update(ev_edit_params)

			# ev_prim_price_table
			ev_prim_price = event.event_primary_prices.last
			ev_prim_price.update(edit_ev_prim_price_params)

			# ev_opt_price_table
			if ev_opt_price_params != 0
				for opt in ev_opt_price_params do
					opt_price = opt.merge(event_id: event.id)
					ev_opt = EventOptionPrice.find_by(event_id: event.id, client_option_price_id: opt["client_option_price_id"])
					if ev_opt.present?
						ev_opt.update(opt_price)
					else
						EventOptionPrice.create(opt_price)
					end
				end
			end

			# ev_states_table
			EventState.create(event_id: event.id, state: "cl_edited", comment: comment_params)

			# 通知メール
			reciever = current_user
			sender = event.customer.user
			if reciever.mail_refused == false
				message = ev_create_params[:message]
				day = ev_hours_params["start_time"].strftime('%Y/%m/%d')
				wday = l(day.to_date, format: :wday)
				start_time = ev_hours_params["start_time"].strftime('%H:%M')
				end_time  = ev_hours_params["end_time"].strftime('%H:%M')
				prefecture = event.prefecture.ja
				location_detail = event.location_detail
				num_people = event.num_people
				total_price = ev_create_params[:total_price]
				primary_price_sum = ev_create_params[:primary_price_sum]
				options = event.event_option_prices
				reciever_mail = reciever.email
				sender_name = sender.name
				link = 'https://www.camera-to-culture.com/' + event.id.to_s
				state = "cl_edited"
				ReserveMailer.ev_state_changed(message, day, wday, start_time, end_time, prefecture, location_detail, num_people, total_price, primary_price_sum, options, reciever_mail, sender_name, link, state).deliver_now
			end

			redirect_to event_path(event)
		end
	end

	def show
		import_current_user
		@event = Event.find(id_params)
		@cl_here = Client.find(@event.client_id)
		@cs_here = Customer.find(@event.customer_id)
		@day = @event.start_time.strftime('%Y/%m/%d')
		@wday = l(@day.to_date, format: :wday)
		@start_time = @event.start_time.strftime('%H:%M')
		@end_time  = @event.end_time.strftime('%H:%M')
		@prefecture = @event.prefecture
		@options = @event.event_option_prices.includes(:client_option_price)
		@ev_prim_price = @event.event_primary_prices.first
		@prim_price = @ev_prim_price.client_primary_price
		@event_state_now = @event.event_states.last
		@ev_photos = @event.event_photos.active
		@ev_photo_nums = @ev_photos.count
		@ev_photos_6 = @event.event_photos.active.limit(6)
		if @event.event_review.present?
			@ev_rev = @event.event_review
		else
			@ev_rev = EventReview.new
		end
		@locale = params[:locale]
	end




private
	#------------ create params -------------#
	def ev_create_params
		# 時間
		start_time = ev_hours_params["start_time"]
		end_time = ev_hours_params["end_time"]
		hours = ev_hours_params["hours"]
		# マイナスならエラーを返す
		if hours <= 0 then
			return "time-error"
		end

		# 撮影価格
		client_id = params[:event][:client_id].to_i
		cl = Client.find(client_id)
		prim_price_ins = cl.client_primary_prices.active.first
		client_primary_price_id = prim_price_ins.id
		prim_price = prim_price_ins.price_per_hour
		primary_price_sum = (prim_price * hours).floor


		# オプション価格
		options = params[:event][:event_option_prices_attributes]
		if options.present?
			option_price_sum = 0
			options.each do |key, value|
				if value.to_i < 0 then
					return "opt-num-error"
				else
					opt = ClientOptionPrice.find(key)
					if opt.along_with_time == true
						option_price = opt.price * value.to_i * hours
					else
						option_price = opt.price * value.to_i
					end
					option_price_sum = (option_price_sum + option_price).floor
				end
			end

			# 合計価格
			total_price = primary_price_sum + option_price_sum
			if total_price <= 0 then
				return "total-fee-error"
			end

			x = params.require(:event).permit(:location_detail, :num_people, :message).merge(client_id: client_id ,customer_id: current_user.id, prefecture_id: params[:prefecture_id].to_i, start_time: start_time, end_time: end_time, total_price: total_price, primary_price_sum: primary_price_sum, option_price_sum: option_price_sum)
			return x
		else
			# 合計価格
			total_price = primary_price_sum
			if total_price <= 0 then
				return "total-fee-error"
			end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_cl_accept.html.erb
<!-- リクエスト承認 -->
<button type="button" class="btn prim-btn ev-states-btn" data-toggle="modal" data-target="#cl_accept">
	<%= t(".Accept") %>
</button>
<!-- リクエスト承認Modal -->
<div class="modal fade" id="cl_accept" tabindex="-1" role="dialog" aria-labelledby="cl_acceptTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="cl_acceptLongTitle"><%= t(".Accept") %></h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<%= form_tag cl_accept_event_event_states_path (event) do %>
				<div class="modal-body">
					<%= text_area_tag 'comment', t(".cl_accept_comment"), class: "ev-state-comment" %>
				</div>
				<div class="modal-footer">
					<%= submit_tag t(".Send"), class: "prim-btn btn" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/events/_cl_dismiss.html.erb
<!-- 撮影を断る -->
<button type="button" class="btn prim-btn ev-states-btn" data-toggle="modal" data-target="#cl_dismiss">
	<%= t(".Dismiss") %>
</button>
<!-- 撮影を断るModal -->
<div class="modal fade" id="cl_dismiss" tabindex="-1" role="dialog" aria-labelledby="cl_dismissTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="cl_dismissLongTitle"><%= t(".Dismiss") %></h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<%= form_tag cl_dismiss_event_event_states_path (event) do %>
				<div class="modal-body">
					<%= text_area_tag 'comment', t(".cl_dismiss_comment"), class: "ev-state-comment" %>
				</div>
				<div class="modal-footer">
					<%= submit_tag t(".Send"), class: "prim-btn btn" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/events/_cs_complain_2.html.erb
<!-- 撮影をキャンセル -->
<button type="button" class="btn prim-btn ev-states-btn" data-toggle="modal" data-target="#cs_complain_2">
	<%= t(".Complain") %>
</button>
<!-- 撮影をキャンセルModal -->
<div class="modal fade" id="cs_complain_2" tabindex="-1" role="dialog" aria-labelledby="cs_complain_2Title" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="cs_complain_2LongTitle"><%= t(".Complain_to_Photographer") %></h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<%= form_tag cs_complain_2_event_event_states_path (event) do %>
				<div class="modal-body">
					<%= text_area_tag 'comment', "", class: "ev-state-comment" %>
				</div>
				<div class="modal-footer">
					<%= submit_tag t(".Send"), class: "prim-btn btn" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/events/_cs_dismiss.html.erb
<!-- 撮影条件変更を断る -->
<button type="button" class="btn prim-btn ev-states-btn" data-toggle="modal" data-target="#cs_dismiss">
	<%= t(".Dismiss_Edited_Condition") %>
</button>
<!-- 撮影条件変更を断るModal -->
<div class="modal fade" id="cs_dismiss" tabindex="-1" role="dialog" aria-labelledby="cs_dismissTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="cs_dismissLongTitle"><%= t(".Dismiss_Edited_Condition") %></h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<%= form_tag cs_dismiss_event_event_states_path (event) do %>
				<div class="modal-body">
					<%= text_area_tag 'comment', t(".cs_dismiss_comment"), class: "ev-state-comment" %>
				</div>
				<div class="modal-footer">
					<%= submit_tag t(".Send"), class: "prim-btn btn" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/events/_cs_recieve.html.erb
<!-- 撮影条件変更を断る -->
<button type="button" class="btn prim-btn ev-states-btn" data-toggle="modal" data-target="#cs_recieve">
	<%= t(".Recieve_photos") %>
</button>
<!-- 撮影条件変更を断るModal -->
<div class="modal fade" id="cs_recieve" tabindex="-1" role="dialog" aria-labelledby="cs_recieveTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="cs_recieveLongTitle"><%= t(".Recieve_photos") %></h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<%= form_tag cs_recieve_event_event_states_path (event),format: :zip do %>
				<div class="modal-body">
					<%= text_area_tag 'comment', t(".cs_recieve_comment"), class: "ev-state-comment" %>
				</div>
				<div class="modal-footer">
					<%= submit_tag t(".download_zip"), class: "prim-btn btn" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/events/_cs_request_cancele.html.erb
<!-- リクエストキャンセル -->
<button type="button" class="btn prim-btn ev-states-btn" data-toggle="modal" data-target="#cs_request_cancele">
	<%= t(".Request_Cancele") %>
</button>
<!-- リクエストキャンセルModal -->
<div class="modal fade" id="cs_request_cancele" tabindex="-1" role="dialog" aria-labelledby="cs_request_canceleTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="cs_request_canceleLongTitle"><%= t(".Request_Cancele") %></h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<%= form_tag cs_request_cancele_event_event_states_path (event) do %>
				<div class="modal-body">
					<%= text_area_tag 'comment', t(".cs_request_cancele_comment"), class: "ev-state-comment" %>
				</div>
				<div class="modal-footer">
					<%= submit_tag t(".Send"), class: "prim-btn btn" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/events/_event_photo.html.erb
<!-- 投稿済みイベントフォト -->
<% if ev_photos.present? %>
  <%= form_tag( r_destroy_event_event_photos_path(@event), method: :delete) do %>
    <div class="container-fluid ev-deliver">
      <h1><%= t(".See_Uploaded_photos") %></h1>
      <div class="container">
        <div class="row">
          <% ev_photos.each do |ev_photo| %>
            <div class="pf col-12 col-sm-6 col-lg-4 maring-b-20">
              <a href="<%= ev_photo.image.url if ev_photo.image? %>" data-lightbox="image-1">
                <div class="pf-img" style="background-image: url(<%= ev_photo.image.thumb.url %>);"></div>
              </a>
              <label class="checkbox float-right">
                <input type="checkbox" name="delete_ev_photo[]" value=<%= ev_photo.id %>>
                <div class="btn btn-sık">
                  <span><%= t(".delete_check")%></span>
                </div>
              </label>
            </div>
          <% end %>
        </div>
        <div class="center-align">
          <%= submit_tag(t(".delete_btn")) %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/events/_event_photo_cs.html.erb
<!-- 投稿済みイベントフォト -->
<% if ev_photos_6.present? %>
  <div class="container-fluid ev-deliver">
    <h1><%= t(".Preview_Uploaded_photos") %></h1>
    <p><%= t(".photo_nums_explanation_1", nums: ev_photo_nums) %></p>
    <p><%= t(".photo_nums_explanation_2", nums: ev_photo_nums) %></p>
    <div class="container">
      <div class="row">
        <% ev_photos_6.each do |ev_photo| %>
          <div class="pf col-12 col-sm-6 col-lg-4 maring-b-20">
            <div class="pf-img" style="background-image: url(<%= ev_photo.image.thumb.url %>);"></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/events/_event_photo_upload.html.erb
<div class="clearfix">
  <h1>
    <%= t(".Upload") %>
  </h1>
  <%= t(".Upload_explanation") %>
  <!-- アップロード箇所 -->
  <div class="file-loading">
      <input id="event_photo" name="event_photo" type="file" multiple>
  </div>
</div>


<script>
<% if locale == "ja" %>
  $("#event_photo").fileinput({
      language: "ja",
      uploadUrl: "/events/<%= event.id %>/event_photos",
      allowedFileExtensions: ["jpg", "png", "jpeg"]
  });
<% elsif locale == "zh" %>
  $("#event_photo").fileinput({
      language: "zh",
      uploadUrl: "/events/<%= event.id %>/event_photos",
      allowedFileExtensions: ["jpg", "png", "jpeg"]
  });
<% elsif locale == "tw" %>
  $("#event_photo").fileinput({
      language: "tw",
      uploadUrl: "/events/<%= event.id %>/event_photos",
      allowedFileExtensions: ["jpg", "png", "jpeg"]
  });
<% else %>
  $("#event_photo").fileinput({
      language: "en",
      uploadUrl: "/events/<%= event.id %>/event_photos",
      allowedFileExtensions: ["jpg", "png", "jpeg"]
  });
<% end %>
</script>
<br>

app/views/events/_event_review_photo.html.erb
<div class="review-photo container">
	<div class="row">
		<% if ev_rev.cs_image_1? %>
			<a href="<%= ev_rev.cs_image_1.url if ev_rev.cs_image_1? %>" data-lightbox="image-1">
				<div class="rview-img" style="background-image: url(<%= ev_rev.cs_image_1.url %>);"></div>
			</a>
		<% end %>
		<% if ev_rev.cs_image_2? %>
			<a href="<%= ev_rev.cs_image_2.url if ev_rev.cs_image_2? %>" data-lightbox="image-2">
				<div class="rview-img" style="background-image: url(<%= ev_rev.cs_image_2.url %>);"></div>
			</a>
		<% end %>
		<% if ev_rev.cs_image_3? %>
			<a href="<%= ev_rev.cs_image_3.url if ev_rev.cs_image_3? %>" data-lightbox="image-3">
				<div class="rview-img" style="background-image: url(<%= ev_rev.cs_image_3.url %>);"></div>
			</a>
		<% end %>
		<% if ev_rev.cs_image_4? %>
			<a href="<%= ev_rev.cs_image_4.url if ev_rev.cs_image_4? %>" data-lightbox="image-4">
				<div class="rview-img" style="background-image: url(<%= ev_rev.cs_image_4.url %>);"></div>
			</a>
		<% end %>
		<% if ev_rev.cs_image_5? %>
			<a href="<%= ev_rev.cs_image_5.url if ev_rev.cs_image_5? %>" data-lightbox="image-5">
				<div class="rview-img" style="background-image: url(<%= ev_rev.cs_image_5.url %>);"></div>
			</a>
		<% end %>
		<% if ev_rev.cs_image_6? %>
			<a href="<%= ev_rev.cs_image_6.url if ev_rev.cs_image_6? %>" data-lightbox="image-6">
				<div class="rview-img" style="background-image: url(<%= ev_rev.cs_image_6.url %>);"></div>
			</a>
		<% end %>
	</div>
</div><!-- endof review-photo -->