config/routes.rb
Rails.application.routes.draw do

	devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

	scope '(:locale)', constraints: { locale: /\w{2}/ } do

		devise_for :users, skip: :omniauth_callbacks, :controllers => {
			registrations: "users/registrations",
			sessions: "users/sessions",
			passwords: "users/passwords",
			confirmations: "users/confirmations",
			unlocks: "users/unlocks",
			mailer: "users/mailer"
		}

		root to: "homes#show"

		resource :home, only: [:show]

		resources :users, only: [:show] do
			collection do
				get 'profile'
				put 'edit_profile'
				get 'account_setting'
				put 'inactive_account'
			end
			resources :messages, only: [:index, :new, :create, :show] do
				collection do
					post 'first_create'
				end
			end
			resources :clients, only: [:edit, :update] do
				resources :client_contacts, only: [:new, :create] do
					collection do
						get 'first_new'
						post 'first_create'
					end
				end
				resources :client_schedules, only: [:index, :create] do
					collection do
						delete 'r_destroy'
					end
				end
			end
		end

		resources :clients, only: [:index, :show] do
			collection do
				get 'pre_month'
				get 'next_month'
			end
			resources :client_portfolios, only: [:new, :create] do
				collection do
					delete 'r_destroy'
				end
			end
		end

		resources :customers, only: [:show]

		resources :events, only: [:new, :create, :show, :edit, :update] do
			collection do
				get 'cs_past'
				get 'cs_future'
				get 'cl_past'
				get 'cl_future'
			end
			resources :event_states, only: []  do
				collection do
					post 'cl_accept'
					post 'cl_deliver'
					post 'cs_recieve'
					post 'cl_edit'
					post 'cs_accept'
					post 'cl_dismiss'
					post 'cs_dismiss'
					post 'cs_cancele'
					post 'cs_request_cancele'
					post 'cl_cancele'
				end
			end
			resources :event_photos, only: [:create] do
				collection do
					delete 'r_destroy'
					get 'zip_dl'
				end
			end
			resources :event_reviews, only: [:create, :update]
		end

		resource :about, only: [:show] do
			collection do
				get 'terms_of_service_cl'
				get 'terms_of_service_cs'
				get 'to_be_a_cameraman'
				get 'how_to_use'
				get 'use_with_phone'
				get 'contact_us'
			end
		end

		resource :helps, only: [:index] do
			collection do
				get 'to_receive_email'
			end
		end

		resources :categories, only: [] do
			collection do
				get 'profile'
				get 'id_photo'
				get 'wedding'
				get 'traveling'
				get 'daily_life'
				get 'seven_five_three'
				get 'coming_of_age'
				get 'maternity'
				get 'new_born'
				get 'commodities'
				get 'event'
				get 'pet'
			end
		end
	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :client_categories
	has_many :event_categories
	has_many :clients, through: :client_categories

	#indexでの検索用
  scope :id_in, -> ids {
    where(id: ids) if ids.present?
  }

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def profile
		import_current_user
		cate_cl_search(1)
		area_cl_search
		area_cl_search
	end

	def id_photo
		import_current_user
		cate_cl_search(2)
		area_cl_search
	end

	def wedding
		import_current_user
		cate_cl_search(3)
		area_cl_search
	end

	def traveling
		import_current_user
		cate_cl_search(4)
		area_cl_search
	end

	def daily_life
		import_current_user
		cate_cl_search(5)
		area_cl_search
	end

	def seven_five_three
		import_current_user
		cate_cl_search(6)
		area_cl_search
	end

	def coming_of_age
		import_current_user
		cate_cl_search(7)
		area_cl_search
	end

	def maternity
		import_current_user
		cate_cl_search(8)
		area_cl_search
	end

	def new_born
		import_current_user
		cate_cl_search(9)
		area_cl_search
	end

	def commodities
		import_current_user
		cate_cl_search(10)
		area_cl_search
	end

	def event
		import_current_user
		cate_cl_search(11)
		area_cl_search
	end

	def pet
		import_current_user
		cate_cl_search(12)
		area_cl_search
	end




end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category_cl_list.html.erb
<% if cls_kanto.present? %>
	<div class="area-name-band"><h3><%= t(".Kanto_area") %></h3></div>
	<div class="container-fluid cate-photographer-list-area">
		<div class="row">
			<% cls_kanto.first(4).each do |cl| %>
				<div class="col-6 col-xl-3">
					<div class="cameraman-lists">
						<div class="cameraman-list-upper">
							<div id="carousel-pf-<%= cl.id %>" class="carousel slide" data-ride="carousel" data-interval="0">
								<%= link_to client_path(cl), target: "_blank", rel: "noopener noreferrer" do %>
									<div class="carousel-inner">
										<div class="carousel-item active">
											<%= image_tag cl.image.thumb.url, :alt => "sample", :class => "cameraman-list-portfolio" if cl.image? %>
										</div>
										<% cl.client_portfolios.each do |pf| %>
											<div class="carousel-item">
												<%= image_tag pf.image.thumb.url, :alt => "sample", :class => "cameraman-list-portfolio" if pf.image? %>
											</div>
										<% end %>
									</div>
								<% end %>
								<a class="carousel-control-prev" href="#carousel-pf-<%= cl.id %>" role="button" data-slide="prev">
									<%= render :partial => 'svgs/cal_left' %>
									<span class="sr-only">Previous</span>
								</a>
								<a class="carousel-control-next" href="#carousel-pf-<%= cl.id %>" role="button" data-slide="next">
									<%= render :partial => 'svgs/cal_right' %>
									<span class="sr-only">Next</span>
								</a>
							</div>
						</div>
						<%= link_to client_path(cl), target: "_blank", rel: "noopener noreferrer" do %>
							<div class="cameraman-list-lower">
								<div class="row">
									<div class="cameraman-list-lower-left col-8">
										<!-- 名前 -->
										<div class="cameraman-list-lower-name"><%= cl.user.name %></div>
										<!-- 値段 -->
										<% cl.client_primary_prices.active.each do |prim_price| %>
											<div class="cameraman-list-lower-price"><%= prim_price.price_per_hour %><%= t(".yen_per_hour") %></div>
										<% end %>
									</div>
									<div class="cameraman-list-lower-right col-4">
										<% if cl.user.image? %>
											<%= image_tag cl.user.image.url(:thumb), alt: "icon", class: "cameraman-list-image" %>
										<% else %>
											<div class="cameraman-list-image">
												<%= render :partial => 'svgs/baby_xs' %>
											</div>
										<% end %>
									</div>
								</div>
							</div>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
<% end %>
<% if cls_kansai.present? %>
	<div class="area-name-band"><h3><%= t(".Kansai_area") %></h3></div>
	<div class="container-fluid cate-photographer-list-area">
		<div class="row">
			<% cls_kansai.first(4).each do |cl| %>
				<div class="col-6 col-xl-3">
					<div class="cameraman-lists">
						<div class="cameraman-list-upper">
							<div id="carousel-pf-<%= cl.id %>" class="carousel slide" data-ride="carousel" data-interval="0">
								<%= link_to client_path(cl), target: "_blank", rel: "noopener noreferrer" do %>
									<div class="carousel-inner">
										<div class="carousel-item active">
											<%= image_tag cl.image.thumb.url, :alt => "sample", :class => "cameraman-list-portfolio" if cl.image? %>
										</div>
										<% cl.client_portfolios.each do |pf| %>
											<div class="carousel-item">
												<%= image_tag pf.image.thumb.url, :alt => "sample", :class => "cameraman-list-portfolio" if pf.image? %>
											</div>
										<% end %>
									</div>
								<% end %>
								<a class="carousel-control-prev" href="#carousel-pf-<%= cl.id %>" role="button" data-slide="prev">
									<%= render :partial => 'svgs/cal_left' %>
									<span class="sr-only">Previous</span>
								</a>
								<a class="carousel-control-next" href="#carousel-pf-<%= cl.id %>" role="button" data-slide="next">
									<%= render :partial => 'svgs/cal_right' %>
									<span class="sr-only">Next</span>
								</a>
							</div>
						</div>
						<%= link_to client_path(cl), target: "_blank", rel: "noopener noreferrer" do %>
							<div class="cameraman-list-lower">
								<div class="row">
									<div class="cameraman-list-lower-left col-8">
										<!-- 名前 -->
										<div class="cameraman-list-lower-name"><%= cl.user.name %></div>
										<!-- 値段 -->
										<% cl.client_primary_prices.active.each do |prim_price| %>
											<div class="cameraman-list-lower-price"><%= prim_price.price_per_hour %><%= t(".yen_per_hour") %></div>
										<% end %>
									</div>
									<div class="cameraman-list-lower-right col-4">
										<% if cl.user.image? %>
											<%= image_tag cl.user.image.url(:thumb), alt: "icon", class: "cameraman-list-image" %>
										<% else %>
											<div class="cameraman-list-image">
												<%= render :partial => 'svgs/baby_xs' %>
											</div>
										<% end %>
									</div>
								</div>
							</div>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
<% end %>

app/views/categories/_category_list.html.erb
<div class="cate-cate-list container">
	<div class="cate-cate-photos row">
		<div class="cate-cate-photo col-4 col-lg-2">
			<%= link_to traveling_categories_path, class: "" do %>
				<div class="sized-square-photo" alt="category-traveling" style='background-image: url("/images/category-traveling-sm.png");'>
					<p><%= t(".traveling") %></p>
				</div>
			<% end %>
		</div>
		<div class="cate-cate-photo col-4 col-lg-2">
			<%= link_to profile_categories_path, class: "" do %>
				<div class="sized-square-photo" alt="category-profile" style='background-image: url("/images/category-profile-sm.png");'>
					<p><%= t(".profile") %></p>
				</div>
			<% end %>
		</div>
		<div class="cate-cate-photo col-4 col-lg-2">
			<%= link_to wedding_categories_path, class: "" do %>
				<div class="sized-square-photo" alt="category-wedding" style='background-image: url("/images/category-wedding-sm.png");'>
					<p><%= t(".wedding") %></p>
				</div>
			<% end %>
		</div>
		<div class="cate-cate-photo col-4 col-lg-2">
			<%= link_to daily_life_categories_path, class: "" do %>
				<div class="sized-square-photo" alt="category-daily-life" style='background-image: url("/images/category-daily-life-sm.png");'>
					<p><%= t(".daily_life") %></p>
				</div>
			<% end %>
		</div>
		<div class="cate-cate-photo col-4 col-lg-2">
			<%= link_to id_photo_categories_path, class: "" do %>
				<div class="sized-square-photo" alt="category-id-photo" style='background-image: url("/images/category-id-photo-sm.png");'>
					<p><%= t(".id_photo") %></p>
				</div>
			<% end %>
		</div>
		<div class="cate-cate-photo col-4 col-lg-2">
			<%= link_to seven_five_three_categories_path, class: "" do %>
				<div class="sized-square-photo" alt="category-seven_five_three" style='background-image: url("/images/category-seven-five-three-sm.png");'>
					<p><%= t(".seven_five_three") %></p>
				</div>
			<% end %>
		</div>
		<div class="cate-cate-photo col-4 col-lg-2">
			<%= link_to coming_of_age_categories_path, class: "" do %>
				<div class="sized-square-photo" alt="category-coming_of_age" style='background-image: url("/images/category-coming-of-age-sm.png");'>
					<p><%= t(".coming_of_age") %></p>
				</div>
			<% end %>
		</div>
		<div class="cate-cate-photo col-4 col-lg-2">
			<%= link_to maternity_categories_path, class: "" do %>
				<div class="sized-square-photo" alt="category-maternity" style='background-image: url("/images/category-maternity-sm.png");'>
					<p><%= t(".maternity") %></p>
				</div>
			<% end %>
		</div>
		<div class="cate-cate-photo col-4 col-lg-2">
			<%= link_to new_born_categories_path, class: "" do %>
				<div class="sized-square-photo" alt="category-new_born" style='background-image: url("/images/category-new-born-sm.png");'>
					<p><%= t(".new_born") %></p>
				</div>
			<% end %>
		</div>
		<div class="cate-cate-photo col-4 col-lg-2">
			<%= link_to commodities_categories_path, class: "" do %>
				<div class="sized-square-photo" alt="category-commodities" style='background-image: url("/images/category-commodities-sm.png");'>
					<p><%= t(".commodities") %></p>
				</div>
			<% end %>
		</div>
		<div class="cate-cate-photo col-4 col-lg-2">
			<%= link_to event_categories_path, class: "" do %>
				<div class="sized-square-photo" alt="category-event" style='background-image: url("/images/category-event-sm.png");'>
					<p><%= t(".event") %></p>
				</div>
			<% end %>
		</div>
		<div class="cate-cate-photo col-4 col-lg-2">
			<%= link_to pet_categories_path, class: "" do %>
				<div class="sized-square-photo" alt="category-pet" style='background-image: url("/images/category-pet-sm.png");'>
					<p><%= t(".pet") %></p>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/categories/coming_of_age.html.erb
<div id="cate-photo" class="cate-photo-coming-of-age">
	<h1>Coming of Age</h1>
	<h2><%= t(".coming-of-age") %></h2>
</div>
<div class="cate-main container">
	<div class="cate-main-photos row">
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/coming-of-age-sample1.png" data-lightbox="image-1" data-title="coming-of-age-photos">
				<div class="sized-square-photo" alt="coming-of-age-photo-sample" style='background-image: url("/images/coming-of-age-sample1.png");'></div>
			</a>
		</div>
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/coming-of-age-sample2.png" data-lightbox="image-1" data-title="coming-of-age-photos">
				<div class="sized-square-photo" alt="coming-of-age-photo-sample" style='background-image: url("/images/coming-of-age-sample2.png");'></div>
			</a>
		</div>
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/coming-of-age-sample3.png" data-lightbox="image-1" data-title="coming-of-age-photos">
				<div class="sized-square-photo" alt="coming-of-age-photo-sample" style='background-image: url("/images/coming-of-age-sample3.png");'></div>
			</a>
		</div>
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/coming-of-age-sample4.png" data-lightbox="image-1" data-title="coming-of-age-photos">
				<div class="sized-square-photo" alt="coming-of-age-photo-sample" style='background-image: url("/images/coming-of-age-sample4.png");'></div>
			</a>
		</div>
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/coming-of-age-sample5.png" data-lightbox="image-1" data-title="coming-of-age-photos">
				<div class="sized-square-photo" alt="coming-of-age-photo-sample" style='background-image: url("/images/coming-of-age-sample5.png");'></div>
			</a>
		</div>
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/coming-of-age-sample6.png" data-lightbox="image-1" data-title="coming-of-age-photos">
				<div class="sized-square-photo" alt="coming-of-age-photo-sample" style='background-image: url("/images/coming-of-age-sample6.png");'></div>
			</a>
		</div>
	</div>
</div>
<hr>


<section class="cate-tips cate-common">
	<h2><%= t(".tips") %></h2>
	<div class="card cate-tips-card">
		<div class="container">
			<div class="row">
				<div class="cate-tips-card-left col-4 inline-center">
					<img alt="coming-of-age-tips1" src="/images/coming-of-age-tips1.png" class="">
				</div>
				<div class="cate-tips-card-right col-8 inline-center">
					<%= simple_format(t(".tips_desc_1")) %>
				</div>
			</div>
		</div>
	</div>
	<div class="card cate-tips-card">
		<div class="container">
			<div class="row">
				<div class="cate-tips-card-left col-4 inline-center">
					<img alt="coming-of-age-tips1" src="/images/coming-of-age-tips2.png" class="">
				</div>
				<div class="cate-tips-card-right col-8 inline-center">
					<%= simple_format(t(".tips_desc_2")) %>
				</div>
			</div>
		</div>
	</div>
	<div class="card cate-tips-card">
		<div class="container">
			<div class="row">
				<div class="cate-tips-card-left col-4 inline-center">
					<img alt="coming-of-age-tips3" src="/images/coming-of-age-tips3.png" class="">
				</div>
				<div class="cate-tips-card-right col-8 inline-center">
					<%= simple_format(t(".tips_desc_3")) %>
				</div>
			</div>
		</div>
	</div>
</section>
<hr>

<% if @cls.count > 0 %>
	<section class="cate-photographer-list cate-common">
		<h2><%= t(".This_category_has_cls", num: @cls.count) %></h2>
		<%= render :partial => 'categories/category_cl_list', :locals=>{cls_kanto: @cls_kanto, cls_kansai: @cls_kansai} %>
	</section>
	<hr>
<% end %>

<section class="cate-common">
	<h2><%= t(".other_categories") %></h2>
	<%= render :partial => 'categories/category_list' %>
</section>

<% assign_meta_tags title: t(".meta_title"),
                    description: t(".meta_description"),
                    keywords: t(".meta_keywords") %>

app/views/categories/commodities.html.erb
<div id="cate-photo" class="cate-photo-commodities">
	<h1>Commodities</h1>
	<h2><%= t(".commodities") %></h2>
</div>
<div class="cate-main container">
	<div class="cate-main-photos row">
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/commodities-sample1.png" data-lightbox="image-1" data-title="commodities-photos">
				<div class="sized-square-photo" alt="commodities-photo-sample" style='background-image: url("/images/commodities-sample1.png");'></div>
			</a>
		</div>
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/commodities-sample2.png" data-lightbox="image-1" data-title="commodities-photos">
				<div class="sized-square-photo" alt="commodities-photo-sample" style='background-image: url("/images/commodities-sample2.png");'></div>
			</a>
		</div>
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/commodities-sample3.png" data-lightbox="image-1" data-title="commodities-photos">
				<div class="sized-square-photo" alt="commodities-photo-sample" style='background-image: url("/images/commodities-sample3.png");'></div>
			</a>
		</div>
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/commodities-sample4.png" data-lightbox="image-1" data-title="commodities-photos">
				<div class="sized-square-photo" alt="commodities-photo-sample" style='background-image: url("/images/commodities-sample4.png");'></div>
			</a>
		</div>
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/commodities-sample5.png" data-lightbox="image-1" data-title="commodities-photos">
				<div class="sized-square-photo" alt="commodities-photo-sample" style='background-image: url("/images/commodities-sample5.png");'></div>
			</a>
		</div>
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/commodities-sample6.png" data-lightbox="image-1" data-title="commodities-photos">
				<div class="sized-square-photo" alt="commodities-photo-sample" style='background-image: url("/images/commodities-sample6.png");'></div>
			</a>
		</div>
	</div>
</div>
<hr>


<section class="cate-tips cate-common">
	<h2><%= t(".tips") %></h2>
	<div class="card cate-tips-card">
		<div class="container">
			<div class="row">
				<div class="cate-tips-card-left col-4 inline-center">
					<img alt="commodities-tips1" src="/images/commodities-tips1.png" class="">
				</div>
				<div class="cate-tips-card-right col-8 inline-center">
					<%= simple_format(t(".tips_desc_1")) %>
				</div>
			</div>
		</div>
	</div>
<!-- 	<div class="card cate-tips-card">
		<div class="container">
			<div class="row">
				<div class="cate-tips-card-left col-4 inline-center">
					<img alt="commodities-tips2" src="/images/commodities-tips2.png" class="">
				</div>
				<div class="cate-tips-card-right col-8 inline-center">
					<%= simple_format(t(".tips_desc_2")) %>
				</div>
			</div>
		</div>
	</div> -->
	<div class="card cate-tips-card">
		<div class="container">
			<div class="row">
				<div class="cate-tips-card-left col-4 inline-center">
					<img alt="commodities-tips3" src="/images/commodities-tips3.png" class="">
				</div>
				<div class="cate-tips-card-right col-8 inline-center">
					<%= simple_format(t(".tips_desc_3")) %>
				</div>
			</div>
		</div>
	</div>
</section>
<hr>


<% if @cls.count > 0 %>
	<section class="cate-photographer-list cate-common">
		<h2><%= t(".This_category_has_cls", num: @cls.count) %></h2>
		<%= render :partial => 'categories/category_cl_list', :locals=>{cls_kanto: @cls_kanto, cls_kansai: @cls_kansai} %>
	</section>
	<hr>
<% end %>

<section class="cate-common">
	<h2><%= t(".other_categories") %></h2>
	<%= render :partial => 'categories/category_list' %>
</section>

<% assign_meta_tags title: t(".meta_title"),
                    description: t(".meta_description"),
                    keywords: t(".meta_keywords") %>

app/views/categories/daily_life.html.erb
<div id="cate-photo" class="cate-photo-daily-life">
	<h1>Daily Life</h1>
	<h2><%= t(".daily-life") %></h2>
</div>
<div class="cate-main container">
	<div class="cate-main-photos row">
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/daily-life-sample1.png" data-lightbox="image-1" data-title="daily-life-photos">
				<div class="sized-square-photo" alt="daily-life-photo-sample" style='background-image: url("/images/daily-life-sample1.png");'></div>
			</a>
		</div>
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/daily-life-sample2.png" data-lightbox="image-1" data-title="daily-life-photos">
				<div class="sized-square-photo" alt="daily-life-photo-sample" style='background-image: url("/images/daily-life-sample2.png");'></div>
			</a>
		</div>
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/daily-life-sample3.png" data-lightbox="image-1" data-title="daily-life-photos">
				<div class="sized-square-photo" alt="daily-life-photo-sample" style='background-image: url("/images/daily-life-sample3.png");'></div>
			</a>
		</div>
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/daily-life-sample4.png" data-lightbox="image-1" data-title="daily-life-photos">
				<div class="sized-square-photo" alt="daily-life-photo-sample" style='background-image: url("/images/daily-life-sample4.png");'></div>
			</a>
		</div>
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/daily-life-sample5.png" data-lightbox="image-1" data-title="daily-life-photos">
				<div class="sized-square-photo" alt="daily-life-photo-sample" style='background-image: url("/images/daily-life-sample5.png");'></div>
			</a>
		</div>
		<div class="cate-main-photo col-4 col-lg-2">
			<a href="/images/daily-life-sample6.png" data-lightbox="image-1" data-title="daily-life-photos">
				<div class="sized-square-photo" alt="daily-life-photo-sample" style='background-image: url("/images/daily-life-sample6.png");'></div>
			</a>
		</div>
	</div>
</div>
<hr>


<section class="cate-tips cate-common">
	<h2><%= t(".tips") %></h2>
	<div class="card cate-tips-card">
		<div class="container">
			<div class="row">
				<div class="cate-tips-card-left col-4 inline-center">
					<img alt="daily-life-tips1" src="/images/commodities-tips1.png" class="">
				</div>
				<div class="cate-tips-card-right col-8 inline-center">
					<%= simple_format(t(".tips_desc_1")) %>
				</div>
			</div>
		</div>
	</div>
	<div class="card cate-tips-card">
		<div class="container">
			<div class="row">
				<div class="cate-tips-card-left col-4 inline-center">
					<img alt="daily-life-tips1" src="/images/seven-five-three-tips2.png" class="">
				</div>
				<div class="cate-tips-card-right col-8 inline-center">
					<%= simple_format(t(".tips_desc_2")) %>
				</div>
			</div>
		</div>
	</div>
	<div class="card cate-tips-card">
		<div class="container">
			<div class="row">
				<div class="cate-tips-card-left col-4 inline-center">
					<img alt="daily-life-tips3" src="/images/daily-life-tips3.png" class="">
				</div>
				<div class="cate-tips-card-right col-8 inline-center">
					<%= simple_format(t(".tips_desc_3")) %>
				</div>
			</div>
		</div>
	</div>
</section>
<hr>


<% if @cls.count > 0 %>
	<section class="cate-photographer-list cate-common">
		<h2><%= t(".This_category_has_cls", num: @cls.count) %></h2>
		<%= render :partial => 'categories/category_cl_list', :locals=>{cls_kanto: @cls_kanto, cls_kansai: @cls_kansai} %>
	</section>
	<hr>
<% end %>

<section class="cate-common">
	<h2><%= t(".other_categories") %></h2>
	<%= render :partial => 'categories/category_list' %>
</section>

<% assign_meta_tags title: t(".meta_title"),
                    description: t(".meta_description"),
                    keywords: t(".meta_keywords") %>